#!/usr/bin/env node

var fs = require('fs-extra');
var output = msg => console.log(msg);
var folderPath = process.argv[2];
var defaultPCId = process.argv[3] || 'unknown';

output('  A tool to upgrade all old version databases files under special folder');
output('    Usage: ./utils/upgradeDatabaseFiles <databaseFolder> [defaultPCId = "unknown"]');
(folderPath && fs.existsSync(folderPath) && fs.statSync(folderPath).isDirectory()) ||
	output('\n  error: please launch this tool by using a param `databaseFolder`(This folder must be exists!)\n' +
		'    such as: `./utils/upgradeDatabaseFiles ./database`\n') + process.exit(1);
	
var up = require(`${__dirname}/../lib/UpgradeDatabaseFiles.js`)
output(`\n  handler folder: ${folderPath}\n` +
	`  default computer Id: ${defaultPCId}`);
process.stdout.write('(y/N) > ');
process.stdin.setEncoding('utf8');
process.stdin.on('data', confirm => {
	process.stdin.pause();
	if (confirm.trim().toLowerCase() != 'y')
		return output('  Action cancelled!');	
	var result = up.upgrade(folderPath, defaultPCId);
	output(`  Upgrade result:\n    files count: ${result.all}\n    upgrade count: ${result.count}\n`);
	output('  Upgrade success!');
});
